### ISSUE TITLE
Define distribution dataset layout

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#10]
A distribution dataset is a superdataset that comprises the complete collection of package for a particular distribution as subdatasets.

TODO:

- should we somehow exposed the latest package version in a particular location (@mih thinks probably not)

**Comment by adswa** [comment]
I don't have a clear opinion yet. Just to understand the TODO, would that be something like this, e.g. a directory with the latest versions of each package (i.e., actual content in the superdataset, not only subdatasets)? 

```
distribution
├── builder            # subds
├── package-1             # subds
│   ├── package_v1.0.0.deb
│   ├── package_v1.0.1.deb
│   └── package_v1.0.2.deb
├── package-2             # subds
│   ├── package_v1.0.0.deb
│   ├── package_v1.0.1.deb
│   └── package_v1.0.2.deb
├── package-3             # subds
│   ├── package_v1.0.0.deb
│   ├── package_v1.0.1.deb
│   └── package_v1.0.2.deb
├── package-4             # subds
│   ├── package_v1.0.0.deb
│   ├── package_v1.0.1.deb
│   └── package_v1.0.2.deb
├── package-5
│   ├── package_v1.0.0.deb
│   ├── package_v1.0.1.deb
│   └── package_v1.0.2.deb
└── packages-latest             # subdir
    ├── package-1
    ├── package-2
    ├── package-3
    ├── package-4
    └── package-5
```

Or would it be a standalone subdataset?

**Comment by mih** [comment]
I think your sketch nicely captures the essence. ATM I see no value for adding these "latest" references. We should be able to figure this out via the VCS dynamically and avoid having to maintain such a representation in addition.
