### ISSUE TITLE
Define archive dataset layout

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#11]
Dataset with the Debian package archive for deploying on a webserver. The layout is largely defined by the structure of such an archive. It may be compartmentalized into particular subdatasets for technical or legal reasons (e.g., separate `non-free`). The archive dataset tracks the dataset for all covered distributions as subdatasets in a particular, non-conflicting location.

Update: Lifting the relevant pieces from #2, amending with the conclusions of concept developments since

```
# a single superdataset tracks the state of the entire operation, entrypoint for
# collaboration maintainer collaboration
# the root of a reprepro-managed archive
/archive
  /conf
  # dedicated subdataset for deploying/mirroring the archive
  /www
    /pool
      /main
      # possibility to split the archive into subdatasets (either for technical reasons, like number of packages,
      # or the need to limit access to particular parts)
      /non-free
      /...
  # the outcome of deb-new-distribution, with all packages hanging off of it
  # this is the input from which the archive will be populated
  /distribution
    /packages/<name1>/...
    /packages/<name2>/...
 ```

One distribution per archive is just one use case. It is also possible to consider multiple distribution datasets per package archive. Maybe better use the pattern establish for the distribution dataset, and do

```
/archive
  /conf
  /www
  /distributions
    /<codename>  # to match conf/distributions
      /packages/<name1>/...
      /packages/<name2>/...
    ...
```

**Comment by adswa** [comment]
Clarifying question: Is this archive the entrypoint for a DataLad-Catalog rendering?

**Comment by mih** [comment]
Now that I started thinking about this again: For a multi-distribution archive (like NeuroDebian), it makes total sense to use the actual archive dataset as the entrypoint for catalog generation -- only this dataset would even know which distributions an archive does provide packages for.

So my original "no" actually needs to be a "possibly" or even a "yes".

**Comment by mih** [comment]
With #81 and #68 done, I think this is settled and can be closed
