### ISSUE TITLE
Installation illusion in python environment

### ISSUE THREAD

**Issue by Manukapp** [psychoinformatics-de/datalad-debian#141]
While working in activated python virtual environment, i.e. `python -m venv my_env`, followed by: `source ./my_env/bin/activate`

**Checking that no datalad debian extension has been installed**
`pip show datalad-debian`
`WARNING: Package(s) not found: datalad-debian`

**Installation**
`python -m pip install datalad-debian`

**Alternative installation** is to `datalad clone https://github.com/psychoinformatics-de/datalad-debian.git` & `pip install -e .` 

These then do the downloading. However, once finished, when trying a command, e.g. `datalad deb-bootstrap-builder` , to see whether the datalad-debian extension is downloaded

Get the following error.
`[WARNING] Failed to load entrypoint datalad_debian from datalad.extensions: ModuleNotFoundError(No module named 'datalad_debian')
datalad: Unknown command 'deb-bootstrap-builder'.  See 'datalad --help'.`

**Importantly**, it works once you `deactivate` (exiting the python environment) and reactivate it, i.e. `source ./my_env/bin/activate`

**Comment by Manukapp** [comment]
Just `rehash`

**Comment by adswa** [comment]
thanks for providing the solution to your issue :) closing
