### ISSUE TITLE
Implement `deb-new-distribution`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#15]
This command is used once in the lifetime of a distribution. It

- creates a new dataset at a given location
- within the dataset, creates a ``builder``subdataset, and configures it as such (via the respective config procedure)

**Comment by aqw** [comment]
Porting conversation from #18, the proposal is to rename this command to `deb-new-distribution`.

**Comment by mih** [comment]
Following the change in #18, rename command.

**Comment by mih** [comment]
https://github.com/psychoinformatics-de/datalad-debian/issues/12#issuecomment-1133233807 documents the state of the implementation, which addresses the current needs.
