### ISSUE TITLE
Implement `deb-bootstrap-builder`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#17]
Given a `builder` package and a builder configuration (see #16), actually create a (containerized) build environment.

**Comment by aqw** [comment]
FTR, I like the idea of unifying the verbs more, so it would make sense if this matched `deb-build-package`, but `deb-build-builder` does feel a bit... odd. ;-)

Just wanted to register the idea, in case anyone comes up with a better idea.

**Comment by adswa** [comment]
Naming suggestion: ``deb-build-setup``

**Comment by aqw** [comment]
The "problem" is that both docker and singularity use the word `build` to... build the container images. So I really feel like it's the right word to use.

Maybe the word `builder` should be changed.

- `deb-build-env`
- `deb-build-container`
- `deb-build-buildenv`

I don't feel like I'm being very creative here... caffeine come to me!

**Comment by aqw** [comment]
No better ideas yet, but I am slowly warming to `deb-build-container`. It's a bit generic, but it is indeed a container (with a run entrypoint), and is invoked by `datalad containers-run`. So I don't think we're exactly off-base.

**Comment by mih** [comment]
I would like avoid the word "container". It fits the current implementation, it does not fit the design. If there is a need to use one and the same verb for establishing the build environment and building a binary package I'd say it is `make`. But I don't like it.

I think the goal of verbal homogeneity does not outweigh the discrepancy with established terms. When calling `debuild` to "build" a package while producing "buildinfo" metadata in a `.buildinfo` file, really calls for "build".

Singularity and docker indeed call container image creation "build" also, but in the Debian context "bootstrap" is also an established term, as is "create"/"update" (looking at the pbuilder, cowbuilder, sbuild) and there are more environments to build in than just singularity/docker containers.

Right now, I am leaning towards `deb-bootstrap-builder`. It seems to play reasonable well with the concept of acting on a "recipe".

I think user "builder", rather than "buildenv" is superior, because the command would touch the entire dataset, rather than just creating a environment of some kind. The initial implementation will, at minimum, also register the buildenv for `containers-run`.

**Comment by mih** [comment]
https://github.com/psychoinformatics-de/datalad-debian/issues/12#issuecomment-1133233807 documents the state of the implementation, which addresses the current needs.
