### ISSUE TITLE
Implement `deb-new-package`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#18]
Given a `distribution` dataset (see #15), adds a subdataset for a given package (name) -- typically the name would match the respective source package name. However, there is no strict requirement for this. One created, the distribution builder dataset is also made a subdataset of the package dataset.

For efficiency reasons, registering the distribution builder would not even need a clone of it into the package dataset. Just registering the subproject commit and copying the `.gitmodules` record would do.

**Comment by aqw** [comment]
One thing I bump on here is the name `deb-add-package`. My first thought is that this command adds an already built package (source, binary, or otherwise).

I propose changing the name to `deb-create-package` (which will match the verb used for `deb-create-distribution` #15).

**Comment by aqw** [comment]
One more idea: change the `create` verb to `new` for both commands.

**Comment by mih** [comment]
This makes sense to me. So `deb-new-package` here?

**Comment by aqw** [comment]
Yes, `deb-new-package` feels intuitive to me.

**Comment by mih** [comment]
https://github.com/psychoinformatics-de/datalad-debian/issues/12#issuecomment-1133233807 documents the state of the implementation, which addresses the current needs.
