### ISSUE TITLE
Update extension setup

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#3]
- [ ] Update from extension template
- [ ] CI uses git-annex from current Debian stable
- [ ] Enable doc-build for PRs on RTD
- [ ] Cross-link documents with http://docs.datalad.org/en/stable/#extension-packages

**Comment by adswa** [comment]
I encountered a blocker.
I added the original extension template as a remote, and rebased the current revision history of this project onto the ones from the extension template. This works, but creates unrelated histories. Someone with appropriate permissions would either need to force-push from https://github.com/adswa/datalad-debian/tree/ex-update, or help me find an alternative updating mechanism.

**Comment by adswa** [comment]
Blocker resolved :)
