### ISSUE TITLE
VM hosting of deb.datalad.org?

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#55]
This would be the place to host a package repository maintained with this extension that is hosting Debian packages for all datalad packages.

It could also host an associate (package) catalog frontend.

**Comment by aqw** [comment]
The VM used for the INM-7 packages and INM-7 NeruoDebian mirror would work well IMO.

Would a naive Apache config (largely a copy of the NeuroDebian mirror) suffice? Or is something more sophisticated needed? (RIA store, etc).

From a DNS standpoint, `deb.datalad.org` should be a CNAME to `www3.hdf.inm7.de`.

**Comment by mih** [comment]
CNAME record is live

**Comment by aqw** [comment]
deb.datalad.org is live. It is available over both HTTP and HTTPS.

How do we want to handle content updates?
1) pull (cron-job)
2) push (on demand)
  - if push, we'll need to figure out permissions and who should have access

**Comment by mih** [comment]
I would want to aim for `pull`. This would boild down to the server entering the checkout of the package archive dataset and run `datalad update --merge` + `datald get .` (or something equivalent).

**Comment by aqw** [comment]
Cool; I also prefer pull.

I'll close this issue, and open a separate, dedicated on for this step.
