### ISSUE TITLE
create INM-7 datalad datastore

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/datalad-debian#58]
My current thoughts are that this will store everything:

- package outputs (binary and source packages, logs, etc)
- package inputs (when binary inputs are necessary [e.g. ISOs])
- distribution, package, and builder repositories
- reprepro outputs and artifacts

There should be user friendly JuGit repos for:
- superdataset of distribution datasets
- "archive" (super)dataset (with `www/` subdataset)
- git repo for each package (already exists)
  - will live as `/upstream` for each package dataset

Thoughts, feedback?

**Comment by aqw** [comment]
Ok, I have created the datastore on `bulk1` as `packaging-debian-inm7.ds.inm7.de`.

I have also created a new sub-group on JuGit called (creatively) `debian`. I have moved `packages-debian` under it and renamed it to `packaging`. There is a new repository (`apt-archive`) to act as a top-level entry point for all datasets.

**Comment by mih** [comment]
Initial dataset pushed to https://jugit.fz-juelich.de/inm7/infrastructure/debian/apt-archive
