### ISSUE TITLE
`deb-new-reprepro-repository` should generate default README

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#72]
Such a dataset is the single entrypoint into a packaging/distribution effort. It makes sense to include basic pointer to this extension and some documentation in a README.

**Comment by mslw** [comment]
Do we have a draft of a workflow / MWE for using `deb-new-reprepro-repository`? I saw [reprepro_demo.sh](https://github.com/psychoinformatics-de/datalad-debian/blob/main/reprepro_demo.sh) but it's not quite what @mih  has shown at the hackathon kick-off meeting.

**Comment by mslw** [comment]
I was thinking more of how it ties with what's produced by `datalad deb-new-distribution` & `deb-build-package`.

But now I understand that the dataset created with `deb-new-reprepro-repository` is an "archive" dataset (using the terms from #6), and its top-level would likely be a place to install the distribution dataset(s)? And then the www directory would get populated with reprepro?
