### ISSUE TITLE
Trim build environment

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-debian#95]
The present container recipe still leaves too much in the container image

- [ ] sources list cache (needs to be updated per build anyways)
- [ ] manpages
- [ ] documentation
- [ ] logs

Removing the logs might also be the path to a reproducible container creation

**Comment by aqw** [comment]
The `-slim` images would remove the documentation/manpages (and some other cruft too).

The post-build cleanup of caches, logs, etc still needs to happen.

**Comment by mih** [comment]
Switching to `-slim` drop the size from
```
-r-xr-xr-x 1 mih mih 200M Aug 20 17:53 singularity-amd64.sif*
```
to 
```
-r-xr-xr-x 1 mih mih 158M Aug 20 18:19 singularity-amd64.sif*
```
for a ready-to-build singularity image for `bullseye`.

Good enough for now, IMHO.
